# Site settings
title: "Marit Larsen lyrics"
description: "An unofficial collection of the lyrics that Marit Larsen has sung."
baseurl: ""
url: "http://lyrics.maritlarsen.ml"

# Build settings
markdown: kramdown
permalink: none
highlighter: pygments
paginate: 3

# Links
links:
  # - title: "Home"
  #   url: /
  - title: "Under the Surface"
    url: /under-the-surface
  - title: "The Chase"
    url: /the-chase
  - title: "Spark"
    url: /spark
  - title: "When The Morning Comes"
    url: /when-the-morning-comes
  - title: "Other songs"
    url: /other
  - title: "About"
    url: /about
